### ISSUE TITLE
docs and installation fails

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-ml#9]
https://webcompat-ml.readthedocs.io/en/latest/installation.html

```
~/code/webcompat-ml % python3 -m venv env
~/code/webcompat-ml % . env/bin/activate
(env) ~/code/webcompat-ml % pip install .
Processing /Users/karl/code/webcompat-ml
Collecting scikit-learn (from webcompat-ml==0.0.1)
  Downloading https://files.pythonhosted.org/packages/2f/c3/431de428dee36c577dec2097130fc5da8ebf8b51b0349e85d1cfa2088595/scikit_learn-0.22.2-cp37-cp37m-macosx_10_9_x86_64.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 3.3MB/s 
Collecting pandas (from webcompat-ml==0.0.1)
  Downloading https://files.pythonhosted.org/packages/ab/ba/f97030b7e8ec0a981abdca173de4e727b3a7b4ed5dba492f362ba87d59a2/pandas-1.0.1-cp37-cp37m-macosx_10_9_x86_64.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 4.3MB/s 
Collecting xgboost (from webcompat-ml==0.0.1)
  Downloading https://files.pythonhosted.org/packages/7d/9d/dcd1e61fd0eeea1c2ed4fa32761e437012776d08530666b5ce843b45fc32/xgboost-1.0.1.tar.gz (820kB)
    100% |████████████████████████████████| 829kB 18.7MB/s 
    Complete output from command python setup.py egg_info:
    ++ pwd
    + oldpath=/private/var/folders/bg/lmsn8jdx47748dbg0nrh2m8h0000gn/T/pip-install-0surdc8j/xgboost
    + cd ./xgboost/
    + mkdir -p build
    + cd build
    + cmake ..
    ./xgboost/build-python.sh: line 21: cmake: command not found
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + cmake .. -DUSE_OPENMP=0
    ./xgboost/build-python.sh: line 27: cmake: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bg/lmsn8jdx47748dbg0nrh2m8h0000gn/T/pip-install-0surdc8j/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/bg/lmsn8jdx47748dbg0nrh2m8h0000gn/T/pip-install-0surdc8j/xgboost/xgboost/libpath.py", line 50, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/bg/lmsn8jdx47748dbg0nrh2m8h0000gn/T/pip-install-0surdc8j/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/bg/lmsn8jdx47748dbg0nrh2m8h0000gn/T/pip-install-0surdc8j/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/bg/lmsn8jdx47748dbg0nrh2m8h0000gn/T/pip-install-0surdc8j/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/karl/code/webcompat-ml/env/xgboost/libxgboost.dylib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bg/lmsn8jdx47748dbg0nrh2m8h0000gn/T/pip-install-0surdc8j/xgboost/
```

**Comment by karlcow** [comment]
I'm trying to figure out things.

start docker on the laptop. 
<img width="247" alt="Capture d’écran 2020-03-02 à 21 12 11" src="https://user-images.githubusercontent.com/505230/75675436-843d9900-5cca-11ea-90bc-abe42af0cac1.png">

```bash
cd webcompat-ml/
pip install -m venv env
. env/bin/activate
(env) ~/code/webcompat-ml % docker build .
Sending build context to Docker daemon  1.616GB
Step 1/4 : FROM python:3.7
3.7: Pulling from library/python
50e431f79093: Pull complete 
dd8c6d374ea5: Pull complete 
c85513200d84: Pull complete 
55769680e827: Pull complete 
f5e195d50b88: Pull complete 
94cdd3612287: Pull complete 
b45109600839: Pull complete 
e0c7a90c35ea: Pull complete 
97fb33d206b1: Pull complete 
Digest: sha256:cd2c65a59a8b2cb2399552642bff1b0c438cb3dd24fe75a08596af94cdfc4659
Status: Downloaded newer image for python:3.7
 ---> f66befd33669
Step 2/4 : WORKDIR /code
 ---> Running in 412d7790e620
Removing intermediate container 412d7790e620
 ---> d910359ff260
Step 3/4 : COPY . /code
 ---> bdf033fcb10a
Step 4/4 : RUN pip install .
 ---> Running in 9c9678e3c7bd
Processing /code
Collecting scikit-learn
  Downloading scikit_learn-0.22.2-cp37-cp37m-manylinux1_x86_64.whl (7.1 MB)
Collecting pandas
  Downloading pandas-1.0.1-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
Collecting xgboost
  Downloading xgboost-1.0.1-py3-none-manylinux1_x86_64.whl (109.7 MB)
Collecting click
  Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting elasticsearch<7
  Downloading elasticsearch-6.4.0-py2.py3-none-any.whl (81 kB)
Collecting certifi
  Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Collecting tqdm
  Downloading tqdm-4.43.0-py2.py3-none-any.whl (59 kB)
Collecting numpy>=1.11.0
  Downloading numpy-1.18.1-cp37-cp37m-manylinux1_x86_64.whl (20.1 MB)
Collecting joblib>=0.11
  Downloading joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Collecting scipy>=0.17.0
  Downloading scipy-1.4.1-cp37-cp37m-manylinux1_x86_64.whl (26.1 MB)
Collecting python-dateutil>=2.6.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting urllib3>=1.21.1
  Downloading urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
Collecting six>=1.5
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: webcompat-ml
  Building wheel for webcompat-ml (setup.py): started
  Building wheel for webcompat-ml (setup.py): finished with status 'done'
  Created wheel for webcompat-ml: filename=webcompat_ml-0.0.1-py3-none-any.whl size=11060 sha256=ece3cb4b5488a0b9960eea26d97366cc6bccaef9cec6b8c554fc6429f666c121
  Stored in directory: /tmp/pip-ephem-wheel-cache-yal5dbbm/wheels/2c/91/06/f2d2f93c2e91eb27eb493240f0cb8ff4b6511d07a0a1f7997d
Successfully built webcompat-ml
Installing collected packages: numpy, joblib, scipy, scikit-learn, six, python-dateutil, pytz, pandas, xgboost, click, urllib3, elasticsearch, certifi, tqdm, webcompat-ml
Successfully installed certifi-2019.11.28 click-7.0 elasticsearch-6.4.0 joblib-0.14.1 numpy-1.18.1 pandas-1.0.1 python-dateutil-2.8.1 pytz-2019.3 scikit-learn-0.22.2 scipy-1.4.1 six-1.14.0 tqdm-4.43.0 urllib3-1.25.8 webcompat-ml-0.0.1 xgboost-1.0.1
Removing intermediate container 9c9678e3c7bd
 ---> 105beb32c782
Successfully built 105beb32c782
```

but then… ? what am I supposed to do to create branches and edit the code.
